services:
  db:
    image: mariadb
    container_name: tickerpark_dev
    ports:
      - 3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - TZ="Asia/Seoul"
      - MYSQL_ROOT_PASSWORD=1q2w3e4r
      - MYSQL_DATABASE=sklee_dev
    restart: always
