spring:
  profiles:
    active: prod
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: com.ticketpark.configuration.mybatis.typeHandler
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler:
logging:
  level:
    com:
      ticketpark:
        mybatis: trace
    org:
      springframework:
        transaction:
          interceptor : trace
        jdbc:
          datasource:
            DataSourceTransactionManager : debug
